<?php

namespace CR\ShopBundle\Repository;

/**
 * Commande_produitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Commande_produitRepository extends \Doctrine\ORM\EntityRepository
{
}
