<?php

namespace CR\ShopBundle\Repository;

/**
 * Image_produitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Image_produitRepository extends \Doctrine\ORM\EntityRepository
{
}
