<?php

namespace CR\ShopBundle\Repository;

/**
 * Liste_recurrenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Liste_recurrenteRepository extends \Doctrine\ORM\EntityRepository
{
}
