<?php

namespace CR\ShopBundle\Repository;

/**
 * produit_categorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class produit_categorieRepository extends \Doctrine\ORM\EntityRepository
{
}
