<?php

namespace CR\ShopBundle\Repository;

/**
 * SouscategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SouscategoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
