<?php

namespace CR\ShopBundle\Repository;

/**
 * user_listeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class user_listeRepository extends \Doctrine\ORM\EntityRepository
{
}
