cr_shop_homepage:
    path:     /accueil
    defaults: { _controller: CRShopBundle:Default:index }

produits:
  path: /produits
  defaults: { _controller: CRShopBundle:Produits:index }


producteurs:
  path: /producteurs
  defaults: { _controller: CRShopBundle:Producteurs:index }

map:
  path: /map
  defaults: { _controller: CRShopBundle:Map:index }

apropos:
  path: /apropos
  defaults: { _controller: CRShopBundle:Apropos:index }

contact:
  path: /contact
  defaults: { _controller: CRShopBundle:Contact:index }
  requirements:
          _method:  GET

boutique:
  path: /boutique/{id}
  defaults: { _controller: CRShopBundle:Producteurs:view }

panier:
  path: /panier
  defaults: { _controller: CRShopBundle:Panier:index }

ajouter:
  path: /ajouter/{id}
  defaults: { _controller: CRShopBundle:Panier:ajouter }

supprimer:
  path: /supprimer/{id}
  defaults: { _controller: CRShopBundle:Panier:supprimer }


vendeur:
  path: /vendeur
  defaults: { _controller: CRShopBundle:Vendeur:show }

vendeur_produit_supprimer:
  path: /vendeur_produit_supprimer/{id}
  defaults: { _controller: CRShopBundle:Vendeur:supprimer }

vendeur_ajoutproduit:
  path: /vendeur/ajoutproduit
  defaults: { _controller: CRShopBundle:Produits:ajout }

vendeur_mesventes:
  path: /vendeur/mesventes
  defaults: { _controller: CRShopBundle:Vendeur:vente }

vendeur_messages:
  path: /vendeur/message
  defaults: { _controller: CRShopBundle:Vendeur:message }

vendeur_comment:
  path: /vendeur/comment
  defaults: { _controller: CRShopBundle:Vendeur:comment }

vendeur_info:
  path: /vendeur/info
  defaults: { _controller: CRShopBundle:Vendeur:info }




paiement:
  path: /paiement
  defaults: { _controller: CRShopBundle:Paiement:index }

paiement_checkout:
  path: /paiement_checkout
  defaults: { _controller: CRShopBundle:Paiement:checkout }

categorie:
  path: /categorie/{id}
  defaults: { _controller: CRShopBundle:Categorie:index }

devenirvendeur:
  path: /devenirvendeur
  defaults: { _controller: CRShopBundle:Devenirvendeur:index }

creation_profil_vendeur:
  path: /creationprofilvendeur
  defaults: { _controller: CRShopBundle:Profilvendeur:index }

creation_profil_vendeur_occ:
  path: /creationprofilvendeurocc
  defaults: { _controller: CRShopBundle:Profilvendeurocc:index }


