cr_shop_homepage:
    path:     /accueil
    defaults: { _controller: CRShopBundle:Default:index }

produits:
  path: /produits
  defaults: { _controller: CRShopBundle:Produits:index }


producteurs:
  path: /producteurs
  defaults: { _controller: CRShopBundle:Producteurs:index }

map:
  path: /map
  defaults: { _controller: CRShopBundle:Map:index }

apropos:
  path: /apropos
  defaults: { _controller: CRShopBundle:Apropos:index }

contact:
  path: /contact
  defaults: { _controller: CRShopBundle:Contact:index }

boutique:
  path: /boutique/{id}
  defaults: { _controller: CRShopBundle:Producteurs:view }

panier:
  path: /panier
  defaults: { _controller: CRShopBundle:Panier:index }

ajouter:
  path: /ajouter/{id}
  defaults: { _controller: CRShopBundle:Panier:ajouter }

supprimer:
  path: /supprimer/{id}
  defaults: { _controller: CRShopBundle:Panier:supprimer }


vendeur:
  path: /vendeur
  defaults: { _controller: CRShopBundle:Produits:ajout }

paiement:
  path: /paiement
  defaults: { _controller: CRShopBundle:Paiement:index }

paiement_checkout:
  path: /paiement_checkout
  defaults: { _controller: CRShopBundle:Paiement:index }

categorie:
  path: /categorie/{id}
  defaults: { _controller: CRShopBundle:Categorie:index }

devenirvendeur:
  path: /devenirvendeur
  defaults: { _controller: CRShopBundle:Devenirvendeur:index }



